relativeURLs = true
title = "Lei Yang"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"

[author]
name = "Lei Yang"
homepage = "http://leiy.me/"

[params]
goatcounter = "leiy"
PGPFingerprint = "2D3EB894C40AE453"
PGPPubkeyLink = "/lei-pgp-pubkey.txt"
shortbio = "Cofounder, Mega Labs"
officeAddress = "32-G918"
officeMapLink = "https://www.csail.mit.edu/sites/default/files/resources/maps/9G/G918.gif"

[markup]
  [markup.highlight]
    style = "solarized-light"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

