relativeURLs = true
title = "Lei Yang"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"

[author]
name = "Lei Yang"
homepage = "http://leiy.me/"

[params]
goatcounter = "leiy"
PGPFingerprint = "2D3EB894C40AE453"
PGPPubkeyLink = "https://keybase.io/yangl1996/pgp_keys.asc?fingerprint=233a3c408f6e5d3fcc13802f2d3eb894c40ae453"
shortbio = "Ph.D. candidate in Computer Science"
officeAddress = "32-G918"
officeMapLink = "https://www.csail.mit.edu/sites/default/files/resources/maps/9G/G918.gif"

[markup]
  [markup.highlight]
    style = "solarized-light"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

